// Guided-tour stops. pos/look are [x, eye height above the floor, d] in plan metres;
// `via` points ([x, d]) steer the camera through doorways between stops.
export const STOPS = [
  {
    title: 'Arrival',
    meta: 'Lot 6706 × 21336 mm · 22 × 70 ft',
    text: 'A single-storey terrace on a quiet, tree-lined street. Warm render, stone-clad piers and a timber-topped swing gate set the tone.',
    pos: [-3.8, 3.0, -8.4],
    look: [3.2, 1.2, 4],
    hold: 7,
  },
  {
    title: 'Gate & Driveway',
    meta: 'Double swing gate · 4.4 m clear opening',
    text: 'The gates swing out over the apron. Pillar lamps and planter boxes frame an interlocking-paver driveway.',
    pos: [2.3, 1.6, -1.9],
    look: [2.8, 1.2, 4],
    hold: 5,
  },
  {
    title: 'Car Porch',
    meta: '6.7 × 5.6 m covered',
    text: 'Room for a full-size sedan with a clear path to the front door, plus a shoe bench and recessed downlights.',
    pos: [1.9, 1.6, 1.7],
    look: [0.8, 1.35, 5.6],
    hold: 6,
  },
  {
    title: 'Living Room',
    meta: '3.0 × 5.0 m · cove-lit ceiling',
    text: 'A walnut slat TV wall faces a deep three-seater. Full-height glazing to the porch brings the evening light right across the marble-look floor.',
    via: [[0.78, 4.7], [0.78, 6.4], [0.85, 8.1], [1.6, 9.3]],
    pos: [2.0, 1.58, 9.9],
    look: [1.0, 1.05, 6.3],
    hold: 7,
  },
  {
    title: 'Dining',
    meta: '3.0 × 5.0 m · seats six',
    text: 'The living spine flows straight into the dining area, lit by a trio of opal glass pendants over an oak table.',
    pos: [2.2, 1.58, 10.25],
    look: [1.2, 0.9, 13.3],
    hold: 6,
  },
  {
    title: 'Kitchen',
    meta: '3.7 × 5.9 m · open plan',
    text: 'Sage cabinetry, quartz worktops and a waterfall island with stools. A skylight pours daylight over the counter.',
    via: [[2.55, 11.4], [2.62, 13.3]],
    pos: [3.4, 1.62, 13.9],
    look: [6.0, 1.0, 17.2],
    hold: 7,
  },
  {
    title: 'Bathroom 2',
    meta: '1.7 × 3.0 m',
    text: 'The common bathroom sits off the kitchen: walk-in shower, timber vanity with mirror and a frosted louvre window.',
    pos: [3.55, 1.6, 15.8],
    look: [3.9, 1.1, 18.6],
    hold: 5,
  },
  {
    title: 'Yard',
    meta: '6.7 × 2.0 m service yard',
    text: 'The back door opens to a covered-drain service yard with space for laundry and a rear gate to the back lane.',
    via: [[4.3, 16.0], [5.25, 16.25], [5.45, 17.7], [5.52, 18.8], [5.52, 19.8]],
    pos: [5.3, 1.6, 20.35],
    look: [1.5, 1.0, 20.7],
    hold: 5,
  },
  {
    title: 'Bedroom 2',
    meta: '3.0 × 3.7 m',
    text: 'Overlooking the yard, with a full-width wardrobe and a dusty-blue feature wall behind the bed.',
    via: [[5.52, 19.6], [5.52, 18.6], [5.3, 16.9], [4.3, 16.0], [3.3, 15.2], [2.47, 15.15]],
    pos: [2.47, 1.6, 16.25],
    look: [0.9, 0.85, 17.8],
    hold: 6,
  },
  {
    title: 'Bedroom 3',
    meta: '3.7 × 2.9 m',
    text: 'Set up as a study-bedroom: a desk under a clay-toned accent wall, a bookshelf and a single bed.',
    via: [[2.47, 15.2], [2.5, 13.4], [2.4, 11.62]],
    pos: [3.75, 1.6, 11.62],
    look: [5.6, 0.8, 12.6],
    hold: 6,
  },
  {
    title: 'Master Bedroom',
    meta: '3.7 × 3.4 m · ensuite',
    text: 'The master faces the street, with a queen bed against a sage headboard wall, a built-in wardrobe and its own bathroom.',
    via: [[2.4, 11.62], [2.3, 9.6], [2.35, 8.47]],
    pos: [3.8, 1.6, 8.5],
    look: [5.8, 0.85, 6.9],
    hold: 7,
  },
  {
    title: 'Ensuite',
    meta: '3.7 × 1.5 m',
    text: 'A glass-screened rain shower, emerald accent tiles and a brass-framed mirror.',
    pos: [4.87, 1.6, 8.3],
    look: [5.0, 1.2, 10.3],
    hold: 6,
  },
  {
    title: 'The Whole Home',
    meta: '3 bed · 2 bath · 22 × 70 ft',
    text: 'Roof off. Three bedrooms, two bathrooms and an open living, dining and kitchen spine on one level. Drag to orbit, or pick a room to walk in.',
    dollhouse: true,
    hold: 12,
  },
];
