(() => {
  const BUTTON_ID = "cm-ai-analyze-button";
  const PANEL_ID = "cm-ai-panel";
  const VALID_LICENSE_KEYS = [
    "CLOSEMATE-DEMO-001",
    "CLOSEMATE-DEMO-002",
    "CLOSEMATE-DEMO-003",
    "CLOSEMATE-LIFETIME-001",
    "CLOSEMATE-LIFETIME-002"
  ];
  const TONES = ["Friendly & Warm","Professional","Soft Closing","Direct Closing","Follow Up","Malay Casual","Malay Professional","Sabah Friendly","Kelantan Friendly"];
  const FALLBACK = {lead_score:0,emotion:"Unknown",objection:"Unable to detect",summary:"Unable to analyze the chat.",suggested_reply:"Maaf, sistem tak dapat analyze chat ni buat masa sekarang. Cuba sekali lagi ya.",follow_up:"Boleh cuba refresh WhatsApp Web dan tekan Analyze Chat semula.",next_action:"Try again"};

  function createAnalyzeButton(){if(document.getElementById(BUTTON_ID))return;const b=document.createElement("button");b.id=BUTTON_ID;b.textContent="Analyze Chat";b.addEventListener("click",()=>document.getElementById(PANEL_ID)?.classList.add("open"));document.body.appendChild(b)}
  function createPanel(){if(document.getElementById(PANEL_ID))return;const p=document.createElement("aside");p.id=PANEL_ID;p.innerHTML=`<div class="cm-panel-header"><h2>CloseMate AI</h2><button id="cm-panel-close" aria-label="Close">×</button></div><div class="cm-panel-content"><div class="cm-config-card"><label class="cm-label" for="cm-license">License Key</label><input id="cm-license" class="cm-input" type="text" placeholder="Enter your license key" /><div class="cm-row"><button id="cm-save-license" class="cm-mini-btn">Save License Key</button><span id="cm-license-status" class="cm-status"></span></div><p class="cm-help">Your license key is required before using Analyze Chat.</p></div><div class="cm-config-card"><label class="cm-label" for="cm-api-key">Gemini API Key</label><div class="cm-inline-field"><input id="cm-api-key" class="cm-input" type="password" placeholder="Enter your Gemini API key" /><button id="cm-toggle-api" class="cm-ghost-btn" type="button">Show</button></div><div class="cm-row"><button id="cm-save-api" class="cm-mini-btn">Save API Key</button><span id="cm-api-status" class="cm-status"></span></div><p class="cm-help">Your Gemini API key is stored only in your browser.</p></div><div class="cm-config-card"><label class="cm-label" for="cm-tone">Reply Tone</label><select id="cm-tone" class="cm-select">${TONES.map((t)=>`<option value="${escapeHtml(t)}">${escapeHtml(t)}</option>`).join("")}</select></div><button id="cm-analyze-btn" class="cm-main-btn">Analyze Chat</button><div id="cm-panel-content-body"><p class="cm-muted">Configure keys, then click Analyze Chat.</p></div></div>`;document.body.appendChild(p);
  document.getElementById("cm-panel-close")?.addEventListener("click",()=>p.classList.remove("open"));bind();load();}
  function bind(){document.getElementById("cm-save-license")?.addEventListener("click",async()=>{await chrome.storage.local.set({closemate_license_key:(document.getElementById("cm-license")?.value||"").trim()});flash("cm-license-status","License key saved")});document.getElementById("cm-save-api")?.addEventListener("click",async()=>{await chrome.storage.local.set({closemate_gemini_api_key:(document.getElementById("cm-api-key")?.value||"").trim()});flash("cm-api-status","API key saved")});document.getElementById("cm-tone")?.addEventListener("change",async(e)=>chrome.storage.local.set({closemate_reply_tone:e.target.value}));document.getElementById("cm-toggle-api")?.addEventListener("click",()=>{const i=document.getElementById("cm-api-key");const b=document.getElementById("cm-toggle-api");const s=i.type==="password";i.type=s?"text":"password";b.textContent=s?"Hide":"Show"});document.getElementById("cm-analyze-btn")?.addEventListener("click",analyze)}
  async function load(){const d=await chrome.storage.local.get(["closemate_license_key","closemate_gemini_api_key","closemate_reply_tone"]);document.getElementById("cm-license").value=d.closemate_license_key||"";document.getElementById("cm-api-key").value=d.closemate_gemini_api_key||"";document.getElementById("cm-tone").value=d.closemate_reply_tone||"Malay Casual";}
  function flash(id,t){const e=document.getElementById(id);if(!e)return;e.textContent=t;setTimeout(()=>e.textContent="",1500)}
  function msgs(){const sels=['[data-testid="msg-container"]','[data-testid="conversation-panel-messages"] [role="row"]','.copyable-text'];const out=[];sels.some((s)=>{const ns=[...document.querySelectorAll(s)];if(!ns.length)return false;ns.forEach((n)=>{const txt=(n.innerText||"").trim();if(!txt)return;const meta=n.getAttribute("data-pre-plain-text")||"";out.push(meta?`${meta} ${txt}`.trim():txt)});return out.length>0});return [...new Set(out)].slice(-80)}
  async function analyze(){const body=document.getElementById("cm-panel-content-body"),btn=document.getElementById("cm-analyze-btn");const license=(document.getElementById("cm-license")?.value||"").trim();const key=(document.getElementById("cm-api-key")?.value||"").trim();const tone=document.getElementById("cm-tone")?.value||"Malay Casual";if(!license)return err("Please enter your license key first.");if(!VALID_LICENSE_KEYS.includes(license))return err("Invalid license key. Please check your key or contact support.");if(!key)return err("Please enter your Gemini API key first.");const messages=msgs();if(!messages.length)return err("No chat messages found. Please open a WhatsApp chat first.");await chrome.storage.local.set({closemate_license_key:license,closemate_gemini_api_key:key,closemate_reply_tone:tone});btn.disabled=true;btn.textContent="Analyzing...";body.innerHTML='<p class="cm-muted">Reading chat and preparing reply...</p>';
  try{const prompt=`You are CloseMate AI, a WhatsApp sales assistant for Malaysian Takaful agents.\n\nAnalyze the visible WhatsApp conversation and return strict valid JSON only.\n\nThe selected reply tone is:\n${tone}\n\nRules:\n- Use natural Malaysian Malay\n- Suitable for WhatsApp\n- Short and copy-paste ready\n- Friendly but sales-oriented\n- Do not sound robotic\n- Do not overpromise\n- Avoid dash symbols in sentences\n- If prospect asks about Medical Card, collect basic details politely\n- If prospect asks about Hibah, explain simply and ask basic details\n- If prospect is cold, reply softly\n- If prospect shows buying intent, guide to quotation or appointment\n\nReturn exact JSON only:\n\n{\n  \"lead_score\": 0,\n  \"emotion\": \"\",\n  \"objection\": \"\",\n  \"summary\": \"\",\n  \"suggested_reply\": \"\",\n  \"follow_up\": \"\",\n  \"next_action\": \"\"\n}\n\nlead_score must be number from 0 to 100.\n\nConversation messages:\n${messages.join("\n")}`;
  const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0.4,responseMimeType:"application/json"}})});
  const d=await r.json();if(!r.ok){const m=String(d?.error?.message||"").toLowerCase();if(m.includes("api key")||m.includes("permission")||m.includes("auth"))return err("Invalid Gemini API key. Please check your API key.");return err("Unable to connect to Gemini API. Please check your API key and internet connection.")}const raw=d?.candidates?.[0]?.content?.parts?.[0]?.text||"{}";render(parse(raw)||FALLBACK)}catch{return err("Unable to connect to Gemini API. Please check your API key and internet connection.")}finally{btn.disabled=false;btn.textContent="Analyze Chat"}}
  function parse(raw){try{return {...FALLBACK,...JSON.parse(raw)}}catch{}const m=raw.match(/\{[\s\S]*\}/);if(!m)return null;try{return {...FALLBACK,...JSON.parse(m[0])}}catch{return null}}
  function err(m){const b=document.getElementById("cm-panel-content-body");if(b)b.innerHTML=`<p class="cm-error">${escapeHtml(m)}</p>`}
  function render(data){const b=document.getElementById("cm-panel-content-body");b.innerHTML=`<div class="cm-grid"><div class="cm-card"><span>Lead Score</span><strong>${Math.max(0,Math.min(100,Number(data.lead_score)||0))/1}/100</strong></div><div class="cm-card"><span>Emotion</span><strong>${escapeHtml(String(data.emotion))}</strong></div></div><div class="cm-block"><h3>Objection</h3><p>${escapeHtml(String(data.objection))}</p></div><div class="cm-block"><h3>Summary</h3><p>${escapeHtml(String(data.summary))}</p></div><div class="cm-block"><div class="cm-block-head"><h3>Suggested Reply</h3><button id="cm-copy-reply" class="cm-copy-btn">Copy Reply</button></div><p class="cm-reply-box">${escapeHtml(String(data.suggested_reply))}</p></div><div class="cm-block"><div class="cm-block-head"><h3>Follow Up</h3><button id="cm-copy-follow-up" class="cm-copy-btn">Copy Follow Up</button></div><p class="cm-reply-box">${escapeHtml(String(data.follow_up))}</p></div><div class="cm-block"><h3>Next Action</h3><p>${escapeHtml(String(data.next_action))}</p></div>`;copy("cm-copy-reply",String(data.suggested_reply),"Copy Reply");copy("cm-copy-follow-up",String(data.follow_up),"Copy Follow Up")}
  function copy(id,text,label){document.getElementById(id)?.addEventListener("click",async()=>{await navigator.clipboard.writeText(text);const b=document.getElementById(id);b.textContent="Copied!";setTimeout(()=>b.textContent=label,1500)})}
  function escapeHtml(t){return t.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
  createAnalyzeButton();createPanel();
})();
